[project]
name = "useful-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai>=2.12.0",
    "pytest>=9.0.2",
]
